# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

run:
  timeout: 5m
linters:
  enable:
   - gofmt
   - errcheck
   - errname
   - errorlint
   - bodyclose
   - durationcheck
   - exhaustive
   - goconst
   - whitespace
