name: Run CI Tests
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - .gitignore
  pull_request:
    paths-ignore:
      - README.md
      - .gitignore
jobs:
  run-lint:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Go
        uses: actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f # v4.0.0
      - name: Setup Go
        uses: hashicorp/setup-golang@v3
        with:
          version-file: go.mod
      - name: Run golangci-lint 
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          version: v1.52.2
          skip-cache: true
  run-tests:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@09d2acae674a48949e3602304ab46fd20ae0c42f # v4.0.0
      - name: Setup Go
        uses: hashicorp/setup-golang@v3
        with:
          version-file: go.mod
      - name: Run Go Vet
        run: |
          go vet ./...
      - name: Run Go Fmt
        run: |
          files=$(go fmt ./...)
          if [ -n "$files" ]; then
            echo "Please run gofmt on these files ..."
            echo "$files"
            exit 1
          fi
      - name: Run Go Test
        run: |
          go test -race -v ./... -coverprofile=coverage.out
      - name: Run Go Bench
        run: |
          go test -bench . -benchmem -v ./...
      - name: Upload Coverage report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
         path: coverage.out
         name: Coverage-report
      - name: Display coverage report
        run: go tool cover -func=coverage.out
      - name: Build Go
        run: go build ./...
