name: Run CI Tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - .gitignore
  pull_request:
    paths-ignore:
      - README.md
      - .gitignore
jobs:
  run-lint:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Go
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - name: Setup Go
        uses: hashicorp/setup-golang@v1
        with:
          version-file: go.mod
      - name: Run golangci-lint 
        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3.7.0
        with:
          version: v1.52.2
          skip-cache: true
  run-tests:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - name: Setup Go
        uses: hashicorp/setup-golang@v1
        with:
          version-file: go.mod
      - name: Run Go Vet
        run: |
          go vet ./...
      - name: Run Go Fmt
        run: |
          files=$(go fmt ./...)
          if [ -n "$files" ]; then
            echo "Please run gofmt on these files ..."
            echo "$files"
            exit 1
          fi
      - name: Run Go Test
        run: |
          go test -race -v ./... -coverprofile=coverage.out
      - name: Run Go Bench
        run: |
          go test -bench . -benchmem -v ./...
      - name: Upload Coverage report
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
        with:
         path: coverage.out
         name: Coverage-report
      - name: Display coverage report
        run: go tool cover -func=coverage.out
      - name: Build Go
        run: go build ./...
        